language: java
sudo: required
dist: trusty
# cache the dependency-check-maven plugin catalog (280MB+)
cache:
  directories: $HOME/.m2/repository/org/owasp/dependency-check-data/
addons:
  apt:
    packages:
      - oracle-java8-installer
      - google-chrome-stable
    sources:
      - google-chrome
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "which chromedriver"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - mvn verify -B jacoco:report coveralls:report
